### ISSUE TITLE
support tcp protocol

### ISSUE THREAD

**Issue by junho85** [fluent-plugins-nursery/fluent-plugin-remote_syslog#10]
i'm using tcp protocol on rsyslog.
it would be better to support tcp protocol.

**Comment by troy** [comment]
Here's more on why, for most situations, this is not a good idea (and for many, is not really possible): https://github.com/papertrail/remote_syslog_logger/pull/7#issuecomment-56122147

It depends how much queuing logic the thing that's calling `remote_syslog_logger` has, but it would be hard for RSL to expose non-blocking writes to that caller without queuing itself.
