### ISSUE TITLE
support for ${} values

### ISSUE THREAD

**Issue by widgetpl** [fluent-plugins-nursery/fluent-plugin-remote_syslog#18]
Is there any possibility to implement such thing like it is in [elasticsearch output plugin](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch_dynamic.rb#L232) ? It would add more possibilities to configure this plugin.
I ment `record\[.+\]` pattern as there is `tag_parts\[.+\]` support alredy.

**Comment by cosmo0920** [comment]
Hi, I'm elasticsearch plugin maintainer.
Plugin specific placeholders like as `${}` is not welcomed recent Fluentd.
Could you show where you want to use placeholder?
Thanks.

**Comment by daipom** [comment]
Sorry for not responding for so long.
We can use the normal placeholders function in the latest version.
So I close this now.
