### ISSUE TITLE
Syslog output

### ISSUE THREAD

**Issue by novitski** [fluent-plugins-nursery/fluent-plugin-remote_syslog#30]
Hello,

How can i use this plugin as simple syslog forworder.

Exemple : if input format is  syslog and i  want to maitin the same message on output. The plugin add somme fileds that i dont need.

Thanks

Ps 👍  Great job

Best regards

**Comment by joker1007** [comment]
`input format is syslog` means that message payload is already syslog protocol format doesn't it?
And so you want to pass raw payload to syslog server.

Thanks! but it is difficult.
fluentd is designed for structual data logging (json, msgpack, etc). And it is difficult to detect detail of inner payload format by fluentd plugin.
To support this feature is too complicated for fluent-plugin-remote_syslog.
Sorry.
