### ISSUE TITLE
Long messages are truncated on UDP

### ISSUE THREAD

**Issue by bivas6** [fluent-plugins-nursery/fluent-plugin-remote_syslog#40]
Hi,

I'm using the plugin for sending to remote syslog over UDP.

Long messages (beyond ~950 chars) are truncated.

Is it possible to split long messages when the transport is UDP?

**Comment by SuvratAgrawal** [comment]
I am also facing the same issue.

**Comment by daipom** [comment]
Sorry for not responding for so long.

In #46, we can also use `packet_size` for UDP.

However, please note that the length should be 1024 bytes or less in RFC3164.

* https://www.rfc-editor.org/rfc/rfc3164
