### ISSUE TITLE
What Chunk keys are assumed in the buffer section?

### ISSUE THREAD

**Issue by vimalk78** [fluent-plugins-nursery/fluent-plugin-remote_syslog#42]
The `write(chunk)` takes out values from chunk using `extract_placeholders`.
Where are the chunk keys specified the plugin? or do you assume there would be <buffer> section which will specify the chunk keys.

**Comment by daipom** [comment]
Sorry for the late reply.

This plugin uses the normal `placeholders` function of Fluentd:

* https://docs.fluentd.org/configuration/buffer-section#placeholders

Example:

```xml
  <match test.**>
    @type remote_syslog
    host "${site}"
    port 22222
    <buffer site>
      flush_mode immediate
    </buffer>
  </match>
```
