### ISSUE TITLE
Do I need to also configure a syslog client in other for remote_syslog to properly send data ?

### ISSUE THREAD

**Issue by leonzo** [fluent-plugins-nursery/fluent-plugin-remote_syslog#43]
Hi

I have installed the [fluent-plugin-remote_syslog](https://github.com/dlackty/fluent-plugin-remote_syslog) in order to send data to a remote rsyslog server trough fluentd

I have the following configuration to send log from a hostA to hostB where a remote Syslog server is configured to collect log on port 514 through tcp or udp)

```
<match log.agent.**>
        @type remote_syslog
        host hostB.com
        port 514
        facility user
        severity notice
        program fluentd
        protocol tcp
        tls false
        hostname hostA.com
        log_level debug

        <buffer>
        </buffer>

        <format>
          @type single_value
          message_key msg
        </format>
</match>
```

After restarting the td-agent service I do not have any td-agent service log error

However, data are not collected in HostB and I am try to understand why ?

My question is : do I need to also configure a syslog client on hostA in other to fluentd to properly send these data ?

Thank You for any help

**Comment by daipom** [comment]
Sorry for the late reply.

No, we don't need to configure a syslog client.

You need to confirm the setting of Fluentd.

```
        <format>
          @type single_value
          message_key msg
        </format>
```

You can remove this unless you want to send only `record["msg"]`.
If the record doesn't have the `msg` key, then it does not send any data.
