### ISSUE TITLE
On the future development of this plugin

### ISSUE THREAD

**Issue by daipom** [fluent-plugins-nursery/fluent-plugin-remote_syslog#47]
Hi @dlackty. First, thanks for developing such a great plugin!

We are @fluent-plugins-nursery team who try to maintain orphaned Fluentd plugins and keep them updated.

It seems that the development of this plugin has been stagnating for a while.
The last update 578380b098fe710255c1559a334064af85829724 is 4 yeas ago and issues and pull requests are left untouched.

Since many users are still relying on this plugin, we want to adopt this plugin as well.

So the question is: is it possible to transfer the ownership of this project to fluent-plugins-nursery?
If you can, we'd continue developing this work as part of our program to sustain the ecosystem.

We are looking forward to hearing back from you!

**Comment by dlackty** [comment]
Hi @daipom
Actually, I've learned the idea of @fluent-plugins-nursery from some Japanese discussion on Twitter, and planned to send an issue to the contact repo asking if this plugin worths your consideration. 

So it's very kind of you to send this issue! I really appreciate it. 

So for the next step, should I send a request on contact repo? Just let me know. Thank you!

**Comment by daipom** [comment]
Thank you for the reply. We really appreciate it!

Now, we just sent a member invitation to you. By accepting it, you will
become a collaborator of [fluent-plugins-nursery](https://github.com/fluent-plugins-nursery/)!

After accepting the invitation:

* Please Transfer this repository to the organization.
  * Detailed instruction is available [here](https://github.com/fluent-plugins-nursery/contact#how-to-transfer-your-plugin).
* And then add @daipom as a Ruby gem owner
  * Run `gem owner fluent-plugin-remote_syslog --add fukuda@clear-code.com` for that.

As explained [here](https://github.com/fluent-plugins-nursery/contact), you will retain the right
to push commits & release new gems after the transfer.

If you have any questions, please feel free to ask me.

**Comment by daipom** [comment]
The transfer is completed at https://github.com/fluent-plugins-nursery/contact/issues/15.
Thank you so much!
