### ISSUE TITLE
Redirect logs to a syslog server based on the value of a field

### ISSUE THREAD

**Issue by mareban** [fluent-plugins-nursery/fluent-plugin-remote_syslog#49]
Hello,

Is it possible for forward log on a dedicated remote syslog server based on the value of a field please (placeholder seems to be supported) ?

  @type remote_syslog
  host  ${record["Site"]}
  port 9514
  
Site will be a fqdn  where the logs should be forwarded !

Thanks for your help

PS : from this, it should be possible isn't it ? https://github.com/fluent-plugins-nursery/fluent-plugin-remote_syslog/pull/31

**Comment by daipom** [comment]
Sorry for the late reply.

You can use placeholders.
This works for me, so it might be possible.

```xml
  <source>
    @type sample
    tag "test"
    sample {"message":"Hello world.","site":"127.0.0.1"}
    rate 1
  </source>
  <match test.**>
    @type remote_syslog
    host "${site}"
    port 22222
    <buffer site>
      flush_mode immediate
    </buffer>
    <format>
      @type "single_value"
      message_key "message"
    </format>
  </match>
  <source>
    @type syslog
    tag "receive"
    port 22222
    bind "127.0.0.1"
  </source>
  <match receive.**>
    @type stdout
  </match>
```
