### ISSUE TITLE
supported format

### ISSUE THREAD

**Issue by mareban** [fluent-plugins-nursery/fluent-plugin-remote_syslog#50]
Hello,

Which syslog format is supported : BSD , IETF, both (how do you select the format) ?

Thanks for your help.

**Comment by daipom** [comment]
Sorry for the late reply.

I'm not sure what format you are referring to.

This plugin is based on rfc3164.

* https://www.rfc-editor.org/rfc/rfc3164

```
<34>Oct 11 22:14:15 mymachine su: 'su root' failed for lonvick on /dev/pts/8
```

please tell me if this is not what you wanted to ask.
