### ISSUE TITLE
Load Balancing

### ISSUE THREAD

**Issue by hazzakins** [fluent-plugins-nursery/fluent-plugin-remote_syslog#55]
Hi,

Is there a way to load balance the destination Syslog servers using this plugin.

Essentially I'm looking to send the output  to 2 syslog collectors without duplicating the messages incase of a service outage on  one of the collectors.

Thanks in advance

**Comment by daipom** [comment]
We can use `roundrobin` plugin!

https://docs.fluentd.org/output/roundrobin

**Comment by hazzakins** [comment]
Cheers @daipom will look into this
