### ISSUE TITLE
Output to remote rsyslog problem

### ISSUE THREAD

**Issue by moodygit** [fluent-plugins-nursery/fluent-plugin-remote_syslog#8]
Hi, I have configured td-agent with remote_syslog plugin. I made data input to td-agent, in parallel I store output data to file in td-agent instance. In file I see changes, but nothing in output to remote rsyslog. Hosts file contain ip/hostname, iptables is down on both instances. Please, help me solve problem, Thanks

**Comment by lijianfeng1993** [comment]
i have save problems

**Comment by daipom** [comment]
Sorry for not responding for so long.
If you still have such problems in the current version,  please reopen this issue and please provide details of the actual settings to reproduce the problems.
